apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: novasuite-backend 
  namespace: develop
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: solutions/argocd/node
    repoURL: https://github.com/sprintug/novasuite-gitops.git
    targetRevision: HEAD
  syncPolicy: {}