apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: mwinel/nginx-devops-lesson:~v0.1
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: solutions/argocd/node
    repoURL: https://github.com/sprintug/novasuite-gitops.git
    targetRevision: main # branch to track
  destination:
    server: https://kubernetes.default.svc # cluster where argocd is running
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
