apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: develop
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sprintdevs/novasuitedata"