namespace: develop
replicas:
  - name: novasuite-backend
    count: 1
images:
  - name: sprintugdevs/novasuite-backend
    
resources:
  - ../../../base

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: dockerconfigjson }]
