apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hms-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: sprintugdevs/novasuite-backend:~^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/update-strategy: latest
    # argocd-image-updater.argoproj.io/allow-tags: "regexp:^[0-9a-f]{7}$"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sprintug/novasuite-gitops
    targetRevision: main # branch to track
    path: environments/dev/app
  destination:
    server: https://kubernetes.default.svc # cluster where argocd is running
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true