apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml

  # - persistent-volume-claim.yaml
  # - persistent-volume.yaml
  # - postgres-deployment.yaml

  # - postgres-service.yaml
  # - secret.yaml