apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvc-hms-system
  namespace: dev
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sprintdevs/hms-dev-vol"
    