apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-novasuite-backend
  namespace: argocd
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sprintdevs/novasuitedata"
    