apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-hms-pv-sys
  namespace: development
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sprintdevs/hms-dev-volume"
    