apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-test
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv-test
  storageClassName: standard