apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-hms-system
  namespace: develop
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: postgres-pvc-hms-system
  storageClassName: standard