apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-hmsys
  # namespace: develop
  namespace: argocd
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv-hmsys
  storageClassName: standard