apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-hms-pvc-system
  namespace: dev
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: postgres-hms-pv-system
  storageClassName: standard