apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-hms
  namespace: develop
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sprintdevs/dev-vol"
    