apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-hms-sys
  namespace: develop
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: postgres-pv-hms-sys
  storageClassName: standard