apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-hms-pvc-sys
  namespace: development
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: postgres-hms-pv-sys
  storageClassName: standard